# Generated by Django 5.1.1 on 2024-10-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('job_announce', 'Job Announce'), ('job_contract', 'Job Contract'), ('chat_message', 'Chat Message'), ('other', 'Other')], max_length=12)),
                ('url', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.accountinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
