# Generated by Django 5.1.1 on 2024-10-04 01:17

import apps.account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_notification"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", apps.account.managers.UserManager()),
            ],
        ),
    ]
