# Generated by Django 5.1.1 on 2024-10-04 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_account_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountinfo",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
