# Generated by Django 5.1.1 on 2024-09-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technology", "0001_initial"),
    ]

    operations = [
       migrations.RunSQL("create extension if not exists pg_trgm")
    ]